### PR TITLE
Draft: Pokraschennya

### PR DESCRIPTION
**Pull request by Mixaill**
## Contents
- [x] common: .gitignore https://github.com/vitaut/modules/pull/4
- [x] CI: initial support https://github.com/vitaut/modules/pull/3
- [x] Clang: std++23 https://github.com/vitaut/modules/pull/5
- [x] Clang: do not overwrite global settings https://github.com/vitaut/modules/pull/7 
- [x] MSVC: initial support https://github.com/vitaut/modules/pull/6
- [x] Modules support detection https://github.com/vitaut/modules/pull/8
- [x] Add fallback example https://github.com/vitaut/modules/pull/13
- [ ] Add `MODULES_ENABLED` property 
- [ ] and the `add_module_sources()` function to delay adding sources
- [ ] Clean up code

## RFC 
* Prefixed functions (prefix was chosen by AI)
Screenshot_20230414_015954

### CODE REVIEW

**Comment by vitaut** [comment]
I would recommend splitting this into smaller PRs.

**Comment by Mixaill** [comment]
@vitaut  For remaining stuff, at least PR #8 should be merged to avoid conflicts

**Comment by vitaut** [comment]
> For remaining stuff, at least PR https://github.com/vitaut/modules/pull/8 should be merged to avoid conflicts

I'll take a look.

**Comment by vitaut** [comment]
I guess this can be closed now. Thanks for your work!

**Pull request closed without merging**
